### PR TITLE
Tidied up example file

### PR DESCRIPTION
**Pull request by mdekauwe**
Hi,

I cleaned up the example file paths to make it all a bit more generic ...

### CODE REVIEW

**Comment by naught101** [comment]
This is more or less duplicated in `/tests/ConvertSpreadsheetToNcdf_AU-How.R` (though less cleanly implemented).

My feeling is that `R/` should basically only contain functions, no scripts (this definitely helps with automated package tools like devtools and roxygen2.

Perhaps this should go in `examples/` and we can delete  `/tests/ConvertSpreadsheetToNcdf_AU-How.R`?

**Comment by aukkola** [comment]
The example_analysis.R was only meant for my use to run the code for now :)

**Comment by mdekauwe** [comment]
I agree with that, making an examples dir seems the best way to go. Are you going to do that or me?

**Comment by mdekauwe** [comment]
Anna you wait till we get a third person :)

**Comment by naught101** [comment]
@aukkola Sure, but I think it makes sense to keep it around, we can use it for testing, and others can use it as a form of documentation. 

@mdekauwe I'm happy to do it

**Comment by aukkola** [comment]
I don't mind. I thought in the final package, best to include a short example in README so it shows up on the github main page

**Comment by naught101** [comment]
ok https://github.com/aukkola/FLUXNET2015_processing/pull/6 is good to go.

R/ConvertSpreadsheetToNcdf.R doesn't work due to the removed source calls. I can try to deal with that separately, unless someone else already is..

**Comment by aukkola** [comment]
I may have removed them by accident. Once the package is working, I'm assuming they'll get sourced automatically?

**Pull request merged**
